# Generated by Django 4.0.2 on 2022-02-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('picture', models.ImageField(null=True, upload_to='news/')),
                ('text', models.TextField(max_length=450, null=True)),
                ('text_ru', models.TextField(max_length=450, null=True)),
                ('text_uz', models.TextField(max_length=450, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
