# Generated by Django 4.0.2 on 2022-02-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_options_alter_news_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainblock',
            name='slider_picture',
            field=models.ImageField(null=True, upload_to='slider_picture'),
        ),
    ]
