# Generated by Django 4.0.2 on 2022-02-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_slider_alter_mainblock_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainblock',
            name='cabinet_counter',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='program_counter',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='student_counter',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='teacher_counter',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
