# Generated by Django 4.0.2 on 2022-02-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mainblock_cabinet_counter_mainblock_program_counter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('name_ru', models.CharField(max_length=120, null=True)),
                ('name_uz', models.CharField(max_length=120, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('description_ru', models.CharField(max_length=250, null=True)),
                ('description_uz', models.CharField(max_length=250, null=True)),
                ('picture', models.ImageField(null=True, upload_to='teachers/')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='slider',
            name='text',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
