# Generated by Django 4.0.2 on 2022-02-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_teachers_options_alter_news_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_ru',
            field=models.TextField(max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_uz',
            field=models.TextField(max_length=210, null=True),
        ),
    ]
