# Generated by Django 4.0.2 on 2022-02-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_news_text_alter_news_text_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='level',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
